# Generated by Django 2.0.7 on 2018-08-20 23:48

from django.db import migrations, models
import src.apps.posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='alguma-tag', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(height_field='height_field', upload_to=src.apps.posts.models.RandomFileName('imgs_uploaded'), verbose_name='Imagem', width_field='width_field'),
        ),
    ]
