# Generated by Django 2.0.8 on 2018-10-04 04:43

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=froala_editor.fields.FroalaField(verbose_name='Conteúdo'),
        ),
    ]
