# Generated by Django 2.0.7 on 2018-07-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='iframe_youtube',
            field=models.CharField(default='ala/ii22', max_length=50, verbose_name='Link do Youtube'),
        ),
    ]
