# Generated by Django 2.0.8 on 2018-10-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181004_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='Generic Subtitle', max_length=120, verbose_name='Subtítulo'),
            preserve_default=False,
        ),
    ]
