# Generated by Django 2.0.7 on 2018-07-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180730_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp', '-updated'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='post',
            name='read_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tempo de leitura'),
        ),
    ]
