# Generated by Django 2.0.7 on 2018-08-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20180820_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='blog', to='posts.Tag', verbose_name='Tag correspondente'),
        ),
    ]
